server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    consul:
      enabled: true
      discovery:
        enabled: true
        query-passing: true
      ribbon:
        enabled: false
    gateway:
      routes:
        - id: multiplication
          uri: lb://multiplication/
          predicates:
            - Path=/challenges/**,/attempts/**,/users/**
        - id: gamification
          uri: lb://gamification/
          predicates:
            - Path=/leaders
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: http://localhost:3000
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - OPTIONS
      default-filters:
        - name: Retry
          args:
            retries: 3
            methods: GET,POST
logging:
  level:
    "[org.springframework.cloud.gateway.handler.predicate]": trace